services:
  elasticsearch:
    image: elasticsearch:9.0.1
    container_name: elasticsearch-benchmark
    environment:
      - node.name=elasticsearch
      - cluster.name=benchmark-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic



volumes:
  elasticsearch_data:
    driver: local

networks:
  elastic:
    driver: bridge